### ISSUE TITLE
Admin Panel - additional

### ISSUE THREAD

**Issue by HardTrain** [HardTrain/StoryTeller#13]
1) Add table's lines for separating data in table

2) Delete PostPhoto collum because it's render photo like array of number

3) Add User.StoryTeller name for both Comments and Posts admin's tables
 
4) In DeletePost and DeleteComment method write " TempData["message"] = string.Format("{0} has been deleted", post.Title);" after "db.SaveChanges()"

5) When you deleting post:
  a)first you need to delete all comments associated with this post, 
  b) then delete post itself

**Comment by IvanMishchenko** [comment]
done deal. What about 1-th I think that it's should write when you be know how should look your admin panel. What do you think about it?

**Comment by IvanMishchenko** [comment]
It's fuck CSS )) I can do it but think its need write on the end

**Comment by HardTrain** [comment]
Totally agree with you, CSS on the end, just add some lines, not like final design, but for better testing

**Comment by IvanMishchenko** [comment]
okay i understand you

**Comment by IvanMishchenko** [comment]
done deal

**Comment by HardTrain** [comment]
Nice
